server:
  port: 8080
logging:
  level:
    root: OFF
    com.hospitalx.emr: INFO
  file:
    name: .logs/emr.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M : %msg%n"
