client:
  # THIS IS YOUR SERVER DOMAIN/IP, REPLACE IT WITH YOUR DOMAIN/IP
  url: "http://localhost:5173"
  # url: "http://kltn-spkt-benhvienx.me/emr"

server:
  servlet:
    context-path: /emr

app:
  jwt:
    rsa:
      private-key: classpath:certs/private.pem
      public-key: classpath:certs/public.pem
    expiresTime: 7
  cookie:
    expiresTime: 7
  cloudinary:
    cloudName: ${CLOUDINARY_CLOUD_NAME}
    apiKey: ${CLOUDINARY_API_KEY}
    apiSecret: ${CLOUDINARY_API_SECRET}

spring:
  application:
    name: emr
  output:
    ansi:
      enabled: DETECT
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: laptrinhwinform2@gmail.com
    password: tgjixkqeibkdunhx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev
