FROM openjdk:oraclelinux8

ENV GOOGLE_CLIENT_ID <YOUR ID HERE>
ENV GOOGLE_CLIENT_SECRET <YOUR SECRET KEY HERE>

WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
COPY src ./src
CMD ["./mvnw", "spring-boot:run"]