FROM openjdk:oraclelinux8

ENV MAIL_USERNAME YOUR EMAIL USE TO SEND EMAIL OF YOUR APPLICATION, example: abc@gmail.com
ENV MAIL_PASSWORD YOUR PASSWORD APPLICATION OF EMAIL, example: password123

ENV MONGODB_URI YOUR CONNECTION STRING TO YOUR MONGODB ATLAS, example: mongodb+srv://mongo123.mongodb.net/?retryWrites=true&w=majority&appName=appnumber1

ENV GOOGLE_CLIENT_ID YOUR ID HERE TO LOGIN WITH GOOGLE, example: myid1234.apps.googleusercontent.com
ENV GOOGLE_CLIENT_SECRET YOUR SECRET KEY HERE, example: keyabc-def-ghijklmn

ENV CLOUDINARY_CLOUD_NAME YOUR CLOUDINARY CLOUD NAME HERE, example: mycloudname
ENV CLOUDINARY_API_KEY YOUR API KEY HERE, example: 1726391873197
ENV CLOUDINARY_API_SECRET YOUR API SECRET HERE, example: AbCdefghIjKlmn

WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
COPY src ./src
CMD ["./mvnw", "spring-boot:run"]